name: PostmanTests
on:
  push:
    branches: [ "main" ]

defaults:
  run:
    working-directory: test/Postman
    
jobs:
  test:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3
      -
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      -
        name: "Install newman"
        run: "npm install -g newman"
      -
        name: "Install newman reporter"
        run: "npm install -g newman-reporter-htmlextra"
      -
        name: "Run tests"
        run: "newman run ReadsOperations.postman_collection.json -e ReadsOperationsVariables.postman_environment.json --env-var \"OmnibeesUser=CMOB1759\" --env-var \"OmnibeesPassword=Ob=1759\""
